version: '3'
services:
  dadou-robot:
    build: .
    #environment:
    #  - DISPLAY=${DISPLAY}
    image: dadouuu/dadou-robot
    ports:
      - "4421:4421"
    volumes:
      - ./dadou_utils:/home/dadou_utils
      - ./dadourobot:/home/dadourobot
      - ./audios:/home/audios
      - ./json:/home/json
      - ./logs:/home/logs
      - ./visuals:/home/visuals
      - ./scripts:/home/scripts
    #  - /tmp/.X11-unix:/tmp/.X11-unix
    #  - /dev/:/dev
    #  - /dev/null:/folder/fileToBeExcluded
    #acc√®s device ACMO gpio serial by id disque etc ...
    privileged: true
 #   devices:
 #    - /dev